HUAN_XIN_USER_NAME: 'blackdust'
HUAN_XIN_APP_NAME: 'huanxin123'
HUAN_XIN_APP_KEY: 'blackdust#huanxin123'
HUAN_CLIENT_ID: 'YXA6qkwFwHDWEeaP2fXUaJuyXA'
HUAN_CLIENT_SECRET: 'YXA6KPQgXyaW8KhRWk2cSVWNsIbv0hA'
